# Generated by Django 4.0.4 on 2022-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('short_desc', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('full_desc', models.TextField(max_length=700, verbose_name='Полное описание')),
                ('picture', models.ImageField(blank=True, upload_to='product/', verbose_name='Предварительная просмотр')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
